name: flutter_app
description: A Flutter frontend for Sunrise
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1

  # Firebase packages
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
